export { default as BoneSurgeries         } from './Bone Surgeries.vue'
export { default as CallFooter            } from './Call_Footer.vue'
export { default as CallStickyBar         } from './Call-Sticky Bar.vue'
export { default as Certificate           } from './Certificate.vue'
export { default as CheckupandAssessments } from './Checkup and Assessments.vue'
export { default as CosmoticSurgeries     } from './Cosmotic Surgeries.vue'
export { default as DentalCare            } from './Dental Care.vue'
export { default as DiagnosticImaging     } from './Diagnostic Imaging.vue'
export { default as DownArrow             } from './Down Arrow.vue'
export { default as EgyptianFlag          } from './Egyptian Flag.vue'
export { default as Emergency274          } from './Emergency274.vue'
export { default as ExpertSurgeon         } from './Expert Surgeon.vue'
export { default as ExternalLink          } from './External Link.vue'
export { default as Facebook              } from './Facebook.vue'
export { default as FullBoardingService   } from './Full Boarding Service.vue'
export { default as HomeVisits            } from './Home Visits.vue'
export { default as IconTooling           } from './IconTooling.vue'
export { default as Instagram             } from './Instagram.vue'
export { default as LanguageSwitcher      } from './Language Switcher.vue'
export { default as Location              } from './Location.vue'
export { default as MedicalDiagnosis      } from './Medical Diagnosis.vue'
export { default as MedicalSuit           } from './MedicalSuit.vue'
export { default as PersonalizedCare      } from './Personalized Care.vue'
export { default as PetPassportIssuance   } from './Pet Passport Issuance.vue'
export { default as PetPaws               } from './Pet Paws.vue'
export { default as PreventiveVaccination } from './Preventive Vaccination.vue'
export { default as StarRating            } from './Star Rating.vue'
export { default as Stethoscope           } from './Stethoscope.vue'
export { default as SurgicalProcedures    } from './Surgical Procedures.vue'
export { default as SurgicalTool          } from './Surgical Tool.vue'
export { default as WhatsAppStickyBar     } from './WhatsApp_StickyBar.vue'